iot.rocketmq.brokers: mt-rocketMqDispatch-vip:9876

logging:
  file: /httx/logs/out.log

server:
  port: 8080

spring:
  profiles:
    active: local

eureka:
  client.healthcheck.enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000

iot:
  service:
    level: 4
    code: ${spring.application.name}

