spring:
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://mt-iotRegistry-1:8080/eureka/
service.name: iotDosBiz
service:
  count:
    limit:
      manager: 10
      token: 20
      data: 10

upload.max.point: 100