spring:
  redis:
    host: localhost
    port: 6379
    timeout: 12000
    lettuce:
      shutdown-timeout: 12000ms
      pool:
        min-idle: 1
feign:
  httpclient:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
service.name: iotDosBiz
service:
  count:
    limit:
      manager: 10
      token: 20
      data: 10

upload.max.point: 100