crsf.whiteList: /400,/500,/404,/417,/csrfTokenServlet
http.url.whiteUrlList: /csrfTokenServlet,/400,/500,/404,/417,/home,/authority/judge
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
service.name: iotDosBiz
spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-active: 100
        min-idle: 8