spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://db-mycat-vip:8066/cm_iotdos?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
spring.datasource.username: admin
spring.datasource.password: 9MeRMf7b15SvsjLpQFtB
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
service.name: iotDosBiz
upload:
  max:
    point: 100
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 12000
    lettuce:
      shutdown-timeout: 12000ms