server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    continue-on-error: true
    druid:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /sys/druid/*
        reset-enable: fasle
        login-username: iotadmin
        login-password: 0plmko
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
    type: com.alibaba.druid.pool.DruidDataSource
  output:
    ansi:
      enabled: always
  application:
    name: des-service
# mybatis 配置
mybatis:
  type-aliases-package: tf56.iot.des.model
  mapper-locations: classpath:mapper/*.xml
  # 配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # 通用 Mapper 配置
mapper:
  not-empty: false
  identity: MYSQL
  mappers: allthings.iot.des.util.IotDesMapper
  # PageHelper 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

zookeeper.connectString: mt-zookeeper-vip:2181
iot.rocketmq.brokers: mt-rocketMqDispatch-vip:9876

eureka:
  client.healthcheck.enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  eureka:
    enabled: true

logging:
  file: /httx/logs/out.log
  path: /httx/logs

iot:
  service:
    level: 4
    code: ${spring.application.name}

