spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/cm_iotdos?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
spring.datasource.username: root
spring.datasource.password: 123456
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
